[package]
name = "mjpeg-rs"
version = "0.1.0"
authors = ["Daisuke Kato"]
edition = "2018"

[dependencies]
actix-rt = "1.0"
actix-web = "2.0"
log = "0.4.8"
env_logger = "0.6"
futures = "0.3.1"
tokio = "0.2"
clap = { version = "2.33.0", features = ["yaml"] }

